apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: calico-ingress-deny
  namespace: bookinfo-data-ns
spec:
  selector: app == 'ratings'
  types:
  - Ingress
  ingress:
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: kubernetes.io/metadata.name == 'bookinfo-services-ns'
      selector: app == 'reviews'
    destination:
      ports:
      - 9080
  - action: Deny
    protocol: TCP
    source:
      namespaceSelector: kubernetes.io/metadata.name == 'bookinfo-frontend-ns'
      selector: app == 'productpage'
    destination:
      ports:
      - 9080
