apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-internal-ingress
  namespace: frontend
spec:
  podSelector:
    matchLabels:
      app: store-front
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: virtual-customer
      ports:
        - protocol: TCP
          port: 8080